### ISSUE TITLE
你好，请问configuration到底有几种参数可选？

### ISSUE THREAD

**Issue by zhongdom** [xilin/ios-build-script#1]
在你的博客中:“在Xcode中选项目，Info tab下会列出所有的configuration，一般有Debug和Release两种”，但是在这里的脚本你用的是Adhoc，能具体说说他们之间的区别吗？我使用Adhoc的pp文件，在“ Adhoc”和“Release”都打包成功了。

**Comment by xilin** [comment]
Project下的每一份configuration都可以在Target中进行不同的设置，相同于一套不同的编译配置集合。
新建configuration的时候可以选择已有的duplicate出来再细化不同的选项。
正常的项目都会预设好Debug和Release两种配置。
你在Target的Build Settings里点任意一项前面的小箭头展开就可以针对不同的configuration做不同的设置。

**Comment by clivexiang** [comment]
no provisioning profile matches "70d465f-803a-43c0-abe5-91f81a259b4e"

这个这么解决， 手动 导出 就可以， 运行脚步到归档完成   导出就不行了 提示错误 如上

**Comment by xilin** [comment]
@clivexiang 你是怎么指定provision profile的？
你本机所有可用的都在`~/Library/MobileDevice/Provisioning Profiles`这个目录下，你可以看一下有哪些

**Comment by zhongdom** [comment]
@xilin 打包的时候可能用到发布到生产证书和Ad Hoc证书，我是直接给显示在开发者帐号上名字的，没有使用~/Library/MobileDevice/Provisioning Profiles里面的名字

**Comment by xilin** [comment]
@zhongdom 我回复的是另一个人哈。之前他在你这个issue下追问了一个问题。再过现在好像被他自己删除了。
你的问题解决了么？OK的话我就close这个issue了。

**Comment by zhongdom** [comment]
@xilin 解决了，close吧
